steps:
  - label: ":docker:"
    plugins:
      - docker-login#v2.0.1:
          username: tylersmalley
      - docker-compose#v3.7.0:
          build: kibana
          image-repository: "tylersmalley/kibana-ci"

  - wait

  - command: .buildkite/scripts/jest_pipeline.sh | buildkite-agent pipeline upload
    label: ":pipeline: Upload"
