steps:
  - label: ":docker:"
    plugins:
      - docker-compose#v3.7.0:
          build: kibana
          image-repository: "gcr.io/elastic-kibana-184716/buildkite/base"

  - wait

  - command: .buildkite/scripts/jest_pipeline.sh | buildkite-agent pipeline upload
    label: ":pipeline: Upload"
